### ISSUE TITLE
Do you support Flac files ? 

### ISSUE THREAD

**Issue by fcollienne-afelio** [mganss/CueGen#11]
Your tool is awesome. 
But unfortunately nothing happens for Flac files : 

nformation: Reading tag for "99983284" from "/Users/XXXXX/XXXX/XXX/XX XX/73 - Bastille - Revolution.flac" 
Information: Found 0 cue points 
Information: Removing existing generated cue points for "99983284" 
Information: Can create 8 cue points 
Information: Updating contentCue "043db43a-054c-4a92-9c6a-35ec40af1d4f" 
Information: Finished cue points creation with errors 

I see cue points in MIK

**Comment by mganss** [comment]
I've added support in 1.0.32.

**Comment by fcollienne-afelio** [comment]
Thank you very much.
I will test it.


De : Michael Ganss ***@***.***>
Date : vendredi, 2 septembre 2022 à 12:07
À : mganss/CueGen ***@***.***>
Cc : Francois Collienne ***@***.***>, Author ***@***.***>
Objet : Re: [mganss/CueGen] Do you support Flac files ? (Issue #11)

I've added support in 1.0.32.
