### ISSUE TITLE
Option to snap to hot cue point

### ISSUE THREAD

**Issue by mobtactics** [mganss/CueGen#12]
Is there an option to set memory cues from a hot cue point? I have already manually set some hot cue points for my tracks but the merge option doesn't seem to work with hot cues. Ideally I would need memory cues 8 or 16 bars from the hot cue point in each direction.

It will also throw an error when running --phrase-length 16 -m -s

Error: Error occurred during creation of cues for "192498168" from "C:/Music/DnB 2022/01 - Break & Total Science - Blame You.mp3" System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* , Int32 )
   at System.Convert.FromBase64String(String s)
   at CueGen.TagFile..ctor(String filePath)
   at CueGen.Content.GetTag()
   at CueGen.Generator.CreateCuesForContent(UInt64& maxId, SQLiteConnection db, Content content)
   at CueGen.Generator.<>c__DisplayClass20_3.<Generate>b__6()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at CueGen.Generator.Generate()

**Comment by SkipperLappen** [comment]
Is the error not because you are having an & in the file name?

**Comment by mobtactics** [comment]
It happens on all 750 tracks so I doubt it's the &. What does work is adding a memory cue on all phrases, it processes all of them. Unfortunately that is of no use to me.

**Comment by mobtactics** [comment]
Closing this issue since I have figured out automating this would be impossible anyway. Drum and bass has too many quirky tracks where phrases are 4 bars longer or shorter for example, it would be pointless to run automation on it.

**Comment by mganss** [comment]
The error probably occurs because the Serato markers are (sometimes) not properly base64-encoded and we're currently not fixing the input string before decoding. See https://github.com/Holzhaus/serato-tags/blob/master/docs/serato_markers2.md

@mobtactics Can you attach one of the offending files here?
