### ISSUE TITLE
Error: Error occurred during creation of cues

### ISSUE THREAD

**Issue by egon43** [mganss/CueGen#13]
Hey. Got this error:
```Error: Error occurred during creation of cues for "XXX" from "XXX" TagLib.UnsupportedFormatException: XXX (taglib/)
   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at CueGen.TagFile..ctor(String filePath)
   at CueGen.Content.GetTag()
   at CueGen.Generator.CreateCuesForContent(UInt64& maxId, SQLiteConnection db, Content content)
   at CueGen.Generator.<>c__DisplayClass20_3.<Generate>b__6()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at CueGen.Generator.Generate()
```

Can you help please? Is it some kind permission issue or something else?

**Comment by egon43** [comment]
Also this
```
Information: Reading tag for "91587853" from "/Users/egonsale/Music/11-2022/16797290_Kiss_(Original Mix).mp3" 
Information: Found 0 cue points 
Information: Removing existing generated cue points for "91587853" 
Information: Can create 7 cue points 
Information: Updating contentCue "b9ed1de4-62e1-454f-84e8-275948a4861c"
 ```

but nothing comest to Rekordbox. No Hotcues or Memory Cues :(

**Comment by egon43** [comment]
This is the track:
[14916083_Rasputin_(Extended Mix).mp3.zip](https://github.com/mganss/CueGen/files/10308140/14916083_Rasputin_.Extended.Mix.mp3.zip)

**Comment by mganss** [comment]
I don't get an exception with the file above. Which command line options did you use?
The file doesn't seem to have MIK cue points.

**Comment by EvzenP** [comment]
> This is the track: [14916083_Rasputin_(Extended Mix).mp3.zip](https://github.com/mganss/CueGen/files/10308140/14916083_Rasputin_.Extended.Mix.mp3.zip)

In your second comment you state different filename - `16797290_Kiss_(Original Mix).mp3` - i.e. it's rather a different track.

**Comment by mganss** [comment]
@egon43 Which command line options did you use?

**Comment by egon43** [comment]
`/Users/egonsale/Music/CueGen.Console --glob=/Users/egonsale/Music/rasputin/ -l file.log -v trace -r`

and response:

```
Information: Starting CueGen version "1.0.34.0" 
Information: Rekordbox database is at "/Users/egonsale/Library/Pioneer/rekordbox/master.db" 
Information: Creating database backup at "/Users/egonsale/Library/Pioneer/rekordbox/master.backup.2023-01-11-19-00-27.db" 
Information: Getting contents from database "/Users/egonsale/Library/Pioneer/rekordbox/master.db" 
Information: 213 contents read 
Information: Getting cues from database "/Users/egonsale/Library/Pioneer/rekordbox/master.db" 
Information: 632 cues read 
Information: Getting contentCues from database "/Users/egonsale/Library/Pioneer/rekordbox/master.db" 
Information: 98 contentCues read 
Information: Getting SongMyTags from database "/Users/egonsale/Library/Pioneer/rekordbox/master.db" 
Information: 0 songMyTags read 
0% [                                                                                                                                                                                                                                     ] 1/1Information: Reading cue points for "162913752" from tag of "/Users/egonsale/Music/rasputin/14916083_Rasputin_(Extended Mix).mp3" 
Information: Reading tag for "162913752" from "/Users/egonsale/Music/rasputin/14916083_Rasputin_(Extended Mix).mp3" 
Information: Found 0 cue points 
Information: Removing existing generated cue points for "162913752" 
Information: Finished cue points creation without errors
```

**Comment by egon43** [comment]
And in Rekordbox there are no Hot Cues or Memory Cues.

**Comment by mganss** [comment]
So the exception no longer occurs?

Regarding the creation of cue points it seems the file does not contain any cue points created by Mixed in Key. Do you want to create Mixed in Key cue points?

**Comment by egon43** [comment]
> 

Yes. But if I give a folder where are other files, then I get also this exception.

**Comment by mganss** [comment]
Let's try to get the cue points working with the Rasputin file first. Have you done the following in Mixed in Key?

> In Mixed in Key you should have Serato integration checked on the settings page and have exported cue points (Click "Export cue points for existing files"). Serato integration writes cue points information to ID3 tags within the media files allowing CueGen to read it.

**Comment by egon43** [comment]
Oh sorry. I should have added this tag  (-p). Everything works now. Also, this exception error is gone 🤷‍♂️
