### ISSUE TITLE
Cue point 32 beats before Chorus

### ISSUE THREAD

**Issue by TraxxMaxx** [mganss/CueGen#18]
Hi,

Thank you for your work, it's a great great tools :)

I would like ask you if possible that create a cue point 32 bets before the Chorus ?

I try with 2 run of your tool but when I start the second run all cue point is deleted ?

I use your tool withe the phaser mode

Thanks

**Comment by mganss** [comment]
I think this should work:

```sh
CueGen.Console -p -o Chorus --of -32
```

This will create cue points only before the start of chorus phrases. It's currently not possible to create cue points with specific offsets for individual phrase types (say, 32 beats before chorus and 16 beats before outro).

**Comment by TraxxMaxx** [comment]
Hi

Thanks for your response

If I run the tool in second time, all cue points are deleted and the tool place only one cue point -32 before chorus, but I use the argument --merge

It's right that the tool delete all cue point ?

**Comment by mganss** [comment]
Yes, when you use `--merge` it deletes all cue points that were created by CueGen itself. But it won't touch the cue points you have created manually. If you don't use `--merge` it will delete all cue points, even those that were created manually. Unfortunately, there is currently no way to offset cue points for specific phrase types only.

I'll leave this issue open as a reminder for future enhancement.

**Comment by TraxxMaxx** [comment]
Thanks for your help

Have nice days

**Comment by SkipperLappen** [comment]
Would be great with this enhancement to your already excellent piece of software :) 

My use case is:

Hotcues to jump to different phrases of the song and memory cues as markers/signals when to mix in or out (offset feature), hence the ability to have both without deleting prior CueGen-generated *cues. Furthermore to have multiple runs of CueGen, i.e. to place af memory cue 32 beats prior to chorus and 16 beats prior to same chorus.

Tia / J
