### ISSUE TITLE
Rekordbox 6.5.x not recognizing the changes

### ISSUE THREAD

**Issue by merfustefan** [mganss/CueGen#4]
Hello,

I’ve used the .exe to set the cue points but it seems that they are not appearing in the rekordbox 6. The progress mark so fine and is executing successfully finishing at 100%. Also I’ve checked the modified date for the .db file and it’s modified when I called the script.

do you have any suggestions? 

Thank you for your work !

**Comment by mganss** [comment]
Please create a log file using log level trace by specifying `-l file.log -v trace` on the command line. It'd be ideal if you could attach the log file to this issue but be aware that it will contain file names of your tracks and other metadata.

**Comment by merfustefan** [comment]
[file.log](https://github.com/mganss/CueGen/files/7078203/file.log)

Thank you for the warning. I just want to fix this problem cause I belive that it is my mistake.

**Comment by mganss** [comment]
There are no cue points from MiK in the files. Have you exported using Serato integration from MiK? From the README:

> In Mixed in Key you should have Serato integration checked on the settings page and have exported cue points (Click "Export cue points for existing files"). Serato integration writes cue points information to ID3 tags within the media files allowing CueGen to read it.

**Comment by merfustefan** [comment]
I've done that, but it seems that the m4a files cannot hold ID3 tags, I've changed to mp3 and surprisingly, it works.
