### ISSUE TITLE
Enhancement: Offset cue 

### ISSUE THREAD

**Issue by SkipperLappen** [mganss/CueGen#6]
Hi, thx for a great piece of software.

One little enhancement wish though. It would be great if you could add an offset backbeat to a drop or phrase group. 

Today a cue is set at the start of a phrase group. If one could add option i.e.  "-backbeat=-16" then the cue would be set 16 beats prior to the start of the phrase.

Hope it makes sense.
Tia

**Comment by mganss** [comment]
I've added this in 1.0.29. The command line option is `--offset=N`, where N is the number of beats (can be negative).
