### ISSUE TITLE
Upgraded MIK 8->10 error

### ISSUE THREAD

**Issue by SkipperLappen** [mganss/CueGen#7]
Hi Michael, 
I've upgraded my MIK to version 10 and I can't get cuegen to add cues to my DB anymore. Is there a way to reset it all?

**Comment by mganss** [comment]
Can you attach your CueGen log file here? 

You can specify the log file location using `-l /path/to/logfile`. Please also specify `-v trace` to enable the most verbose logging level.

**Comment by SkipperLappen** [comment]
Hi Michael

Start of log file is attached. 

Another thing - it was me who requested the offset functionality. Very quick response and solution, thank you.

Is it possible to only make an offset cue with different phrases? 
My use case is that I want to add a hot cue 16 and 8 beats prior to ex. Verse and Chorus. And to place hot cue on start of other phrases.
I would be okay run CueGen.console in 2 or 3 iterations.

Tia/Jacob

**Comment by mganss** [comment]
The log file didn't come through. I think you need to attach it via GitHub's web interface.

The offset cue for only specific phrases should be possible. If you want regular cue points on the other phrases as well you will need to create them in two passes. You can select the phrase types via the phrase group order argument (`-o`), e.g. `-o Verse,Chorus` for only verse and chorus.

**Comment by SkipperLappen** [comment]
> The log file didn't come through. I think you need to attach it via GitHub's web interface.

[logfile.txt](https://github.com/mganss/CueGen/files/8102256/logfile.txt)

**Comment by mganss** [comment]
Please try [version 1.0.31](https://github.com/mganss/CueGen/releases/tag/v1.0.31).

**Comment by SkipperLappen** [comment]
> Please try [version 1.0.31](https://github.com/mganss/CueGen/releases/tag/v1.0.31).

Works perfect! Thank you.
